[package]
name = "protohackers-solutions"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
tokio = { version = "1.23.0", features = ["full"] }
