[package]
name = "protohackers-solutions"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.10.5"
serde = {version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
tokio = { version = "1.24.2", features = ["full"] }
